[package]
name = "chacha-blake3"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aead = "0.5"
zeroize = "1.6"
chacha20 = "0.9"
blake3 = "1.4"